package com.seb.projecttitancore.client;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.seb.projecttitancore.ProjectTitanCore;
import net.minecraft.core.Vec3i;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * Loads and serves the Titan projection voxel data from
 * {@code data/projecttitancore/structure/titan.json}. Generated by
 * {@code scripts/gen_titan_structure.py}.
 *
 * <p>The JSON groups voxels by tier and by color so the renderer can iterate
 * cumulative tiers (1..N) and submit each color in one batch.
 */
public final class TitanProjection {

    public enum Color {
        IVORY(0xECE4D0),
        SHADOW(0x8A6620),
        GOLD(0xFFE054);

        public final int rgb;
        Color(int rgb) { this.rgb = rgb; }
    }

    private static final String RESOURCE_PATH = "/data/projecttitancore/structure/titan.json";

    /** Indexed by tier 1..MAX_TIER. Each map holds per-color voxel lists for that tier alone. */
    private final Map<Integer, Map<Color, List<Vec3i>>> byTier;
    public final int maxTier;

    private TitanProjection(Map<Integer, Map<Color, List<Vec3i>>> byTier) {
        this.byTier = byTier;
        this.maxTier = byTier.keySet().stream().mapToInt(Integer::intValue).max().orElse(0);
    }

    public List<Vec3i> voxels(int tier, Color color) {
        Map<Color, List<Vec3i>> tierMap = byTier.get(tier);
        if (tierMap == null) return List.of();
        List<Vec3i> list = tierMap.get(color);
        return list != null ? list : List.of();
    }

    // --- Lazy singleton ---------------------------------------------------

    private static volatile TitanProjection instance;

    public static TitanProjection get() {
        TitanProjection local = instance;
        if (local == null) {
            synchronized (TitanProjection.class) {
                local = instance;
                if (local == null) {
                    local = load();
                    instance = local;
                }
            }
        }
        return local;
    }

    private static TitanProjection load() {
        try (InputStream in = TitanProjection.class.getResourceAsStream(RESOURCE_PATH)) {
            if (in == null) {
                ProjectTitanCore.LOGGER.error("Titan projection resource missing: {}", RESOURCE_PATH);
                return new TitanProjection(Map.of());
            }
            JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8))
                    .getAsJsonObject();
            JsonArray tiers = root.getAsJsonArray("tiers");

            Map<Integer, Map<Color, List<Vec3i>>> result = new java.util.HashMap<>();
            for (int i = 0; i < tiers.size(); i++) {
                JsonObject tierEntry = tiers.get(i).getAsJsonObject();
                int tier = tierEntry.get("tier").getAsInt();
                JsonObject colorsJson = tierEntry.getAsJsonObject("colors");

                Map<Color, List<Vec3i>> colorMap = new EnumMap<>(Color.class);
                for (Color c : Color.values()) {
                    String key = c.name().toLowerCase();
                    if (!colorsJson.has(key)) continue;
                    JsonArray voxArr = colorsJson.getAsJsonArray(key);
                    List<Vec3i> voxList = new ArrayList<>(voxArr.size());
                    for (int j = 0; j < voxArr.size(); j++) {
                        JsonArray xyz = voxArr.get(j).getAsJsonArray();
                        voxList.add(new Vec3i(xyz.get(0).getAsInt(), xyz.get(1).getAsInt(), xyz.get(2).getAsInt()));
                    }
                    colorMap.put(c, voxList);
                }
                result.put(tier, colorMap);
            }
            return new TitanProjection(result);
        } catch (Exception e) {
            ProjectTitanCore.LOGGER.error("Failed to load titan projection data", e);
            return new TitanProjection(Map.of());
        }
    }
}
